{
 "title": "Go Metrics",
 "tags": [
  "go",
  "golang"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(go_goroutines, job)"
   },
   {
    "name": "project",
    "query": "label_values(go_goroutines{job=\"$job\"}, project)"
   },
   {
    "name": "env",
    "query": "label_values(go_goroutines{job=\"$job\", project=\"$project\"}, env_name)"
   },
   {
    "name": "stage",
    "query": "label_values(go_goroutines{job=\"$job\", project=\"$project\", env_name=\"$env\"}, stage)"
   },
   {
    "name": "service",
    "query": "label_values(go_goroutines{job=\"$job\", project=\"$project\"}, service)"
   }
  ]
 },
 "panels": [
  {
   "title": "Mem stats utiliser",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memstats_alloc_bytes" }
   ]
  },
  {
   "title": "Mem stats utiliser",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memstats_alloc_bytes" }
   ]
  },
  {
   "title": "Memoire Total",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "process usage cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{}[10m])",
     "legendFormat": "{{service}}-{{instance}}"
    }
   ]
  },
  {
   "title": "process cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(irate(node_cpu_seconds_total{}[5m]))",
     "legendFormat": "{{service}}-{{instance}}"
    }
   ]
  },
  {
   "title": "process cpu AVERAGE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 - avg by(instance)(irate(node_cpu_seconds_total{}[5m])))",
     "legendFormat": "{{service}}-{{instance}}"
    }
   ]
  },
  {
   "title": "process cpu Instant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[30m])) * 100) ",
     "legendFormat": "{{service}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Temperature HWMON",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{sensor=\"temp1\"}"
    },
    {
     "expr": "node_hwmon_temp_celsius{sensor=\"temp3\"}"
    }
   ]
  },
  {
   "title": "Voltage HWMON",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_hwmon_in_volts" }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{}",
     "legendFormat": "go_memstats_heap_alloc_bytes-{{service}}-{{instance}}"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{}",
     "legendFormat": "go_memstats_heap_sys_bytes-{{service}}-{{instance}}"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{}",
     "legendFormat": "go_memstats_heap_idle_bytes-{{service}}-{{instance}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{}",
     "legendFormat": "go_memstats_heap_inuse_bytes-{{service}}-{{instance}}"
    },
    {
     "expr": "go_memstats_heap_released_bytes{}",
     "legendFormat": "go_memstats_heap_released_bytes-{{service}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Memory in Off-Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{}",
     "legendFormat": "go_memstats_mspan_inuse_bytes-{{service}}-{{instance}}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{}",
     "legendFormat": "go_memstats_mspan_sys_bytes-{{service}}-{{instance}}"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{}",
     "legendFormat": "go_memstats_mcache_inuse_bytes-{{service}}-{{instance}}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{}",
     "legendFormat": "go_memstats_mcache_sys_bytes-{{service}}-{{instance}}"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{}",
     "legendFormat": "go_memstats_buck_hash_sys_bytes-{{service}}-{{instance}}"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{}",
     "legendFormat": "go_memstats_gc_sys_bytes-{{service}}-{{instance}}"
    },
    {
     "expr": "go_memstats_other_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", service=~\"$service\"} - go_memstats_other_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", service=~\"$service\"}",
     "legendFormat": "bytes of memory are used for other runtime allocations {pod={{kubernetes_pod_name}}}"
    },
    {
     "expr": "go_memstats_next_gc_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", service=~\"$service\"}",
     "legendFormat": "go_memstats_next_gc_bytes-{{service}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "graph",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{}[10m])",
     "legendFormat": "{{service}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{}",
     "legendFormat": "go_memstats_stack_inuse_bytes-{{service}}-{{instance}}"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{}",
     "legendFormat": "go_memstats_stack_sys_bytes-{{service}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "go_memstats_sys_bytes{}", "legendFormat": "{{service}}-{{instance}}" }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_goroutines{}", "legendFormat": "{{service}}-{{instance}}" }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_memstats_mallocs_total{}", "legendFormat": "{{service}}-{{instance}}" }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "go_gc_duration_seconds{}", "legendFormat": "{{service}}-{{instance}}" }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences",
   "type": "graph",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{}[10m])",
     "legendFormat": "{{service}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Memoire Free",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memstats_frees_total" }
   ]
  },
  {
   "title": "Memoire Libre Swap",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_SwapFree_bytes" }
   ]
  },
  {
   "title": "Memoire Low Libre",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_LowFree_bytes" }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{}[10m])",
     "legendFormat": "{{service}}-{{instance}}"
    }
   ]
  },
  {
   "title": "NetStat IPv6 In",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_netstat_Ip6_InOctets" }
   ]
  },
  {
   "title": "NetStat IPv6 out",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_netstat_Ip6_OutOctets" }
   ]
  },
  {
   "title": "Disk Read rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{}[5m])",
     "legendFormat": "{{service}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed_total{}[5m])",
     "legendFormat": "{{service}}-{{instance}}"
    }
   ]
  },
  {
   "title": "NetStat IN / OUT",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_netstat_IpExt_OutOctets" },
    { "expr": "node_netstat_IpExt_InOctets" }
   ]
  },
  {
   "title": "Mémoire allocations d'exécution",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_memstats_other_sys_bytes" }
   ]
  },
  {
   "title": "Prochain cycle GC",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memstats_next_gc_bytes" }
   ]
  },
  {
   "title": "Octets MCache de l'OS -Goroutine",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_memstats_mcache_sys_bytes" },
    { "expr": "go_memstats_mcache_inuse_bytes" }
   ]
  },
  {
   "title": "Etendues de mémoire de la pile",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_memstats_stack_sys_bytes" },
    { "expr": "go_memstats_stack_inuse_bytes " },
    { "expr": "go_memstats_stack_idle_bytes " }
   ]
  },
  {
   "title": "Octets MSpan de l'OS (nombre de pages)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_memstats_mspan_sys_bytes" },
    { "expr": "go_memstats_mspan_inuse_bytes" }
   ]
  },
  {
   "title": "Mémoire métadonnées",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_memstats_gc_sys_bytes" }
   ]
  }
 ]
}